complete fp2
Peredery/study pull request #4
Opened 2021-04-22 17:43 UTC by Peredery

2021-04-23 14:38 UTC, nut4k1 requested changes

2021-04-23 14:38 UTC, nut4k1 commented on test/exercise/fp2/solution.rb
> +        my_each { |e| result << e unless e.nil? }
надо через reduce

2021-04-26 08:58 UTC, Andrew8xx8 requested changes

2021-04-26 08:58 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        size.times do |i|
`each` нужно реальзовать используя рекурсию

2021-04-26 08:58 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_compact
`compact` нужно реализовать через `reduce`

2021-04-26 08:58 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        result = MyArray.new
`map` нужно реализовать через `reduce`

2021-04-26 08:58 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_each { |e| acc = acc.nil? ? e : yield(acc, e) }
`reduce` нужно реализовать используя рекурсию

2021-04-27 12:05 UTC, Peredery commented
Всё исправил

2021-04-29 09:48 UTC, Andrew8xx8 requested changes

2021-04-29 09:48 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_each(&block)
Нужно либо использовать &func, либо yield это разный способ сделать одно и тоже, передать блок

2021-04-29 12:29 UTC, Peredery commented on test/exercise/fp2/solution.rb
> +      def my_each(&block)
понял, исправил на то что хотел "&func"

2021-04-30 10:44 UTC, Andrew8xx8 approved these changes

2021-04-30 10:45 UTC, merged